replicaCount: 1

image:
  repository: imagerepository/starfire-dev-01-templateApps
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

serviceAccount:
  create: false
  automount: false
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

fluxcdImageUpdate:
  enabled: true
  fluxcdNamespace: flux-system
  extraLabels: {}
  imageRepository:
    interval: 3m0s
    secretRef: harbor-registry-secret
  imagePolicy:
    filterTags:
      pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)\.giteaci$'
    policy:
      semver:
        range: '>22.10.10-x'
  webhookReceiver:
    secretRef: webhook-token
