apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloud-platfrom-frontend
spec:
  releaseName: cloud-platfrom-frontend
  chart:
    spec:
      chart: starfire-templates-app
      sourceRef:
        kind: HelmRepository
        name: starfire-harbor-repo-public
        namespace: flux-system
      version: "0.1.15"
  interval: 1h0m0s
  timeout: 15m0s
  install:
    disableWait: true
    remediation:
      retries: 15
  upgrade:
    disableWait: true
    remediation:
      retries: 15
  valuesFrom:
    - kind: Secret
      name: values-cloud-platfrom-frontend
