_internal_defaults_do_not_set:
  hub: registry.istio.io/release
  tag: 1.30.1
  variant: ""
  image: ztunnel
  network: ""
  global:
    networkPolicy:
      enabled: false
  resourceName: ""
  labels: {}
  annotations: {}
  volumeMounts: []
  volumes: []
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
  podAnnotations:
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
  podLabels: {}
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  resourceQuotas:
    enabled: false
    pods: 5000
  peerCaCrl:
    enabled: false
  imagePullSecrets: []
  env: {}
  imagePullPolicy: ""
  multiCluster:
    clusterName: ""
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
  terminationGracePeriodSeconds: 30
  revision: ""
  caAddress: ""
  xdsAddress: ""
  istioNamespace: istio-system
  logLevel: info
  logAsJson: false
  seLinuxOptions: {}
  resourceScope: all
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  dnsPolicy: ""
  dnsConfig: {}
