#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 <namespace> <service-name>"
  echo "  e.g.: $0 starfire-dev-01 base-gateway"
  exit 1
}

[[ $# -ne 2 ]] && usage

NAMESPACE="$1"
SERVICE="$2"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APPS_DIR="$(cd "$SCRIPT_DIR/../apps" && pwd)"
OUT_DIR="$APPS_DIR/$NAMESPACE/$SERVICE"

if [[ -d "$OUT_DIR" ]]; then
  echo "Error: $OUT_DIR already exists"
  exit 1
fi

mkdir -p "$OUT_DIR"

# kustomizeconfig.yaml
cat > "$OUT_DIR/kustomizeconfig.yaml" <<'EOF'
# Kustomize config for enabling HelmRelease values from
# ConfigMaps and Secrets generated by Kustomize
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
EOF

# kustomization.yaml
cat > "$OUT_DIR/kustomization.yaml" <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: values-${SERVICE}
    files:
      - values.yaml=values.yaml
resources:
  - release.yaml
EOF

# release.yaml
cat > "$OUT_DIR/release.yaml" <<EOF
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${SERVICE}
spec:
  releaseName: ${SERVICE}
  chart:
    spec:
      chart: template-app
      sourceRef:
        kind: HelmRepository
        name: repo
        namespace: flux-system
      version: "0.1.14"
  interval: 1h0m0s
  timeout: 15m0s
  install:
    disableWait: true
    remediation:
      retries: 15
  upgrade:
    disableWait: true
    remediation:
      retries: 15
  values:
    fluxcdImageUpdate:
      enabled: false
      fluxcdNamespace: flux-system
  valuesFrom:
    - kind: Secret
      name: values-${SERVICE}
EOF

# values.yaml
TODAY=$(date '+%Y-%m-%d_%H:%M:%S')
cat > "$OUT_DIR/values.yaml" <<EOF
application:
  addtime: '${TODAY}'
  description: '${NAMESPACE}/${SERVICE}'

image:
  repository: harbor.zevpa.com/${NAMESPACE}/${SERVICE} # {"\$imagepolicy": "flux-system:${NAMESPACE}-${SERVICE}:name"}
  tag: '' # {"\$imagepolicy": "flux-system:${NAMESPACE}-${SERVICE}:tag"}

replicaCount: "1"
revisionHistoryLimit: 10

envFrom:
  - configMapRef:
      name: configmap-base

env:
  JAVA_OPTS: -Duser.timezone=Asia/Shanghai -XX:+UseContainerSupport -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0

service:
  enabled: true
  type: ClusterIP
  name: http
  servicePort: 8080
  targetPort: 8080

resources:
  limits:
    cpu: '1'
    memory: 2Gi
  requests:
    cpu: '1'
    memory: 2Gi

livenessProbe:
  enabled: true
  probeType: "httpGet"
  port: 8081
  path: "/actuator/health"
  initialDelaySeconds: 30
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  enabled: true
  probeType: "httpGet"
  port: 8081
  path: "/actuator/health"
  initialDelaySeconds: 30
  timeoutSeconds: 5
  scheme: "HTTP"
startupProbe:
  enabled: true
  probeType: "httpGet"
  port: 8081
  path: "/actuator/health"
  scheme: "HTTP"
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 25
  periodSeconds: 15

lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 10"]

terminationGracePeriodSeconds: 45

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 30
        preference:
          matchExpressions:
            - key: pay-mode
              operator: In
              values:
                - monthly
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 80
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ${SERVICE}
        topologyKey: failure-domain.beta.kubernetes.io/zone


persistence:
  enabled: false
  type: nfs
  volumes:
    - name: nfsdata
      mount:
        path: /data/nfs
  nfs:
    server: nfs-server
    path: /nfsdata/data

fluxcdImageUpdate:
  enabled: true
  fluxcdNamespace: flux-system
  imageRepository:
    interval: 1m0s
    secretRef: harbor-private-registry
  imagePolicy:
    filterTags:
      pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-.+-.\.gitlabci$
    policy:
      semver:
        range: '>22.10.10-x'
  webhookReceiver:
    secretRef: webhook-token

EOF

echo "✅ Created: $OUT_DIR"
echo "   kustomizeconfig.yaml  kustomization.yaml  release.yaml  values.yaml"
echo ""
echo "Next steps:"
echo "  1. Fill in application.appid / gitlab / teamleader / tier in values.yaml"
echo "  2. Set image.tag"
echo "  3. Commit and push"
