apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: starfire-harbor-repo-public
spec:
  type: "oci"
  interval: 15m0s
  timeout: 5m0s
  insecure: true
  url: oci://harbor.zevpa.com/repo
  secretRef:
    name: oci-auth-starfire-harbor-repo-public
---
apiVersion: v1
kind: Secret
metadata:
  name: oci-auth-starfire-harbor-repo-public
data:
  username: "YWRtaW4="
  password: "SGFyYm9yMTIzNDU="
type: Opaque