apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1h
  url: oci://ghcr.io/istio-release/charts/istio-operator
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.24.x"
